name: Update README with branch names

on:
  push:
    branches: [main]

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Fetch latest changes
        run: git fetch

      - name: Generate list of branches
        run: |
          echo "[Branches]" > branches.txt
          git branch --remote --list "origin/Challenge/*" | sed "s/origin\///" | sed "s/Challenge\///" >> branches.txt

      - name: Update README
        uses: peaceiris/actions-readme@v2.1.1
        with:
          readme-path: README.md
          replace-text: '[Branches]'
          insert-text: "$(cat branches.txt)"

      - name: Commit changes
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"
          git commit -am "Update list of branches"
          git push
